// Локализованные подписи схем ScenarioFlows (десктоп + мобилка).
// Ключ = один визуальный ряд (tspan). RU по умолчанию, EN — для casesEn.
// Автогенерировано; правки текста здесь, геометрия — в *.astro.
export type FlowLang = 'ru' | 'en';

export const flowStrings: Record<FlowLang, Record<string, string>> = {
  ru: {
      "hdrManualAnswer": "РУЧНОЙ ОТВЕТ",
      "hdrOrderStatus": "СТАТУС ЗАКАЗА",
      "hdrAnswer": "ОТВЕТ",
      "hdrPayShipStatus": "СТАТУС ОПЛАТЫ И ОТГРУЗКИ",
      "hdrAsksLogist": "УТОЧНЯЕТ У ЛОГИСТА",
      "hdrAnswerAfter": "ОТВЕТ ПОСЛЕ СВЕРКИ",
      "hdrShipStatus": "СТАТУС ОТГРУЗКИ",
      "blindL1": "Слепая зона CRM: не",
      "blindL2": "видно, что отгружено и",
      "blindL3": "что осталось",
      "crmFullL1": "CRM даёт полный",
      "crmFullL2": "статус?",
      "mgrOpens": "Менеджер открывает",
      "clientAskL1": "Клиент: «где мой",
      "clientAskL2": "заказ?»",
      "answersClientNow": "Сразу отвечает клиенту",
      "checksWms": "Проверяет WMS",
      "crossExcel": "Сверяет Excel",
      "checksErp": "Проверяет ERP",
      "givesManual": "Даёт ручной ответ",
      "reads3L1": "Считывает 3 прогресс-",
      "reads3L2": "бара",
      "popoverShip": "Pop-over отгрузок",
      "problemFirstL1": "Проблемные позиции",
      "problemFirstL2": "первыми",
      "answersSpecific": "Отвечает с конкретикой",
      "needDetails": "Нужны детали?",
      "answersBarsL1": "Отвечает по прогресс-",
      "answersBarsL2": "барам",
      "noLinkL1": "Нет связи счёт ↔",
      "noLinkL2": "отгрузка ↔ оплата:",
      "noLinkL3": "ответ собирается",
      "noLinkL4": "вручную",
      "clearPaidL1": "Понятно, что",
      "clearPaidL2": "оплачено и где",
      "clearPaidL3": "просрочка?",
      "financeAskL1": "Финансист: «что",
      "financeAskL3": "просрочка?»",
      "answersNowL1": "Сразу отвечает",
      "answersFinL2": "финансисту",
      "comesBackL1": "Возвращается с",
      "comesBackL2": "выводом",
      "seesShipPaid": "Видит Shipped 50% / Paid",
      "showsProblemL1": "Показывает проблемные",
      "showsProblemL2": "позиции",
      "answerBreakdownL1": "Ответ с разбивкой по",
      "answerBreakdownL2": "счетам",
      "anyOverdue": "Есть просрочка?",
      "explainsSvp": "Объясняет shipped vs",
      "noRemainL1": "Не видно остаток заказа:",
      "noRemainL2": "CRM не связывает заказ",
      "noRemainL3": "и текущую отгрузку",
      "clearClosedL1": "Понятно, закрыт",
      "clearClosedL2": "ли заказ?",
      "logistAskL1": "Логист: «отгрузка",
      "logistAskL2": "собрана — она",
      "logistAskL3": "последняя?»",
      "answersLogistNow": "Сразу отвечает логисту",
      "asksLogist": "Уточняет у логиста",
      "givesAfterCheck": "Даёт ответ после сверки",
      "readsShippedL1": "Считывает «Shipped",
      "readsShippedL2": "100/200»",
      "answersNotLastL1": "Отвечает: не последняя,",
      "answersNotLastL2": "ещё ~100",
      "enoughData": "Хватает данных?",
      "looksPopover": "Смотрит pop-over",
      "answerLayoutL1": "Ответ с раскладкой",
      "answerLayoutL2": "остатка"
  },
  en: {
      "hdrManualAnswer": "MANUAL ANSWER",
      "hdrOrderStatus": "ORDER STATUS",
      "hdrAnswer": "ANSWER",
      "hdrPayShipStatus": "PAYMENT & SHIPMENT STATUS",
      "hdrAsksLogist": "ASKS LOGISTICS",
      "hdrAnswerAfter": "ANSWER AFTER CHECK",
      "hdrShipStatus": "SHIPMENT STATUS",
      "blindL1": "CRM blind spot: can’t",
      "blindL2": "see what’s shipped and",
      "blindL3": "what’s left",
      "crmFullL1": "Does CRM give the",
      "crmFullL2": "full status?",
      "mgrOpens": "Manager opens",
      "clientAskL1": "Client: “where’s my",
      "clientAskL2": "order?”",
      "answersClientNow": "Answers the client at once",
      "checksWms": "Checks WMS",
      "crossExcel": "Cross-checks Excel",
      "checksErp": "Checks ERP",
      "givesManual": "Gives a manual answer",
      "reads3L1": "Reads 3 progress",
      "reads3L2": "bars",
      "popoverShip": "Shipments pop-over",
      "problemFirstL1": "Problem items",
      "problemFirstL2": "first",
      "answersSpecific": "Answers with specifics",
      "needDetails": "Need details?",
      "answersBarsL1": "Answers from the",
      "answersBarsL2": "progress bars",
      "noLinkL1": "No invoice ↔",
      "noLinkL2": "shipment ↔ payment link:",
      "noLinkL3": "the answer is pieced",
      "noLinkL4": "together by hand",
      "clearPaidL1": "Clear what’s",
      "clearPaidL2": "paid and where",
      "clearPaidL3": "it’s overdue?",
      "financeAskL1": "Finance: “what’s",
      "financeAskL3": "it’s overdue?”",
      "answersNowL1": "Answers the",
      "answersFinL2": "finance team at once",
      "comesBackL1": "Comes back with",
      "comesBackL2": "a conclusion",
      "seesShipPaid": "Sees Shipped 50% / Paid",
      "showsProblemL1": "Shows the problem",
      "showsProblemL2": "line items",
      "answerBreakdownL1": "Answer broken down",
      "answerBreakdownL2": "by invoice",
      "anyOverdue": "Anything overdue?",
      "explainsSvp": "Explains shipped vs",
      "noRemainL1": "Order remainder unclear:",
      "noRemainL2": "CRM doesn’t link the order",
      "noRemainL3": "to the current shipment",
      "clearClosedL1": "Clear whether the",
      "clearClosedL2": "order is closed?",
      "logistAskL1": "Logistics: “shipment’s",
      "logistAskL2": "packed — is it the",
      "logistAskL3": "last one?”",
      "answersLogistNow": "Answers logistics at once",
      "asksLogist": "Asks the logistician",
      "givesAfterCheck": "Answers after checking",
      "readsShippedL1": "Reads “Shipped",
      "readsShippedL2": "100/200”",
      "answersNotLastL1": "Answers: not the last,",
      "answersNotLastL2": "~100 to go",
      "enoughData": "Enough data?",
      "looksPopover": "Checks the pop-over",
      "answerLayoutL1": "Answer with the",
      "answerLayoutL2": "remainder laid out"
  },
};
